name: 'ecoscan SAST'
description: 'Static Code Analysis for ecobee Repositories'
inputs:
  language:
    description: 'Language to scan'
    required: true
    default: 'go'
  directory:
    description: 'Directory to scan (defaults to all directories recursively)'
    required: false
outputs:
  result:
    description: "The result of running ecoScan"
    value: ${{ steps.sast.outputs.ecoscan_result }}
  sarif_b64_output:
    description: "The sarif output of the scan results in base64 format"
    value: ${{ steps.sast.outputs.ecoscan_sarif_b64 }}
runs:
  using: "composite"
  steps:
    - run: echo "Running ecoscan Static Code Analysis for ${{inputs.language }}..."
      shell: bash
    - id: sast
      run: ${{ github.action_path }}/../lib/ecoscan.sh
      shell: bash
      env:
        INPUT_LANG: ${{ inputs.language }}
        INPUT_DIR:  ${{ inputs.directory }}
