name: 'ecoscan SAST'
description: 'Static Code Analysis for ecobee Repositories'
inputs:
  language:
    description: 'Language to scan'
    required: true
    default: 'go'
  directory:
    description: 'Directory to scan (defaults to all directories recursively)'
    required: false
runs:
  using: "composite"
  steps:
    - run: echo "Running ecoscan Static Code Analysis for ${{inputs.language }}..."
      shell: bash
    - run: pwd
      shell: bash
    - run: ls -lah
      shell: bash
    - run: ../lib/ecoscan.sh
      shell: bash
      env:
        INPUT_LANG: ${{ inputs.language }}
        INPUT_DIR:  ${{ inputs.directory }}
